export default [
    {
        klander: ["Strube"],
        klandret: ["Panini"],
        beskrivelse: "DAT7?",
        med: 22,
        mod: 1,
    },
    {
        klander: ["FUNÉ"],
        klandret: ["Strube"],
        beskrivelse: "Normal mad",
        med: 13,
        mod: 6,
    },
    {
        anti: true,
        klander: ["FUNÉ"],
        klandret: ["Dolan"],
        beskrivelse: "Støttemand?",
        konklusion: ["FUNÉ", "Strube", "Panini"],
    },
    {
        klander: ["Asbjørn"],
        klandret: ["Strube", "Panini", "Dolan"],
        beskrivelse: "Kampråb",
        med: 17,
        mod: 5,
    },
    {
        anti: true,
        klander: ["Hjalte"],
        klandret: ["Strube", "Panini", "Dolan"],
        beskrivelse: "De er nice",
        konklusion: [
            "Jacob R.",
            "Alexander",
            "Mikkel Mus",
            "Emil S.",
            "Niels Jakob",
            "Jacob W.",
            "Benjamin"
        ],
    },
    {
        klander: ["Panini"],
        klandret: ["Dolan"],
        beskrivelse: "Poker lån",
        med: 14,
        mod: 9,
    },
    {
        anti: true,
        klander: ["Panini"],
        klandret: ["Niels Jakob"],
        beskrivelse: "Oplader",
        konklusion: ["Panini"]
    },
    {
        klander: ["FUNÉ"],
        klandret: ["Panini"],
        beskrivelse: "Afbyder",
        med: 13,
        mod: 2
    },
    {
        klander: ["Jacob R."],
        klandret: ["FUNÉ"],
        beskrivelse: "Niels Jakob med c",
        med: 14,
        mod: 7,
    },
    {
        klander: ["Dolan"],
        klandret: ["Panini"],
        beskrivelse: "Dolan er rus",
        med: 13,
        mod: 13,
    },
    // 
    {
        klander: ["FUNÉ"],
        klandret: ["Panini"],
        beskrivelse: "Ingen russer?",
        med: 11,
        mod: 6,
    },
    {
        klander: ["Niels Jakob"],
        klandret: ["FUNÉ"],
        beskrivelse: "Kæmpehelt",
        anti: true,
        konklusion: [
            "Niels Jakob", 
            "Hjalte", 
            "FUNÉ", 
            "Emil S.", 
            "Asbjørn",
            "Benjamin",
        ]
    },
    {
        klander: ["Strube"],
        klandret: ["Emil S."],
        beskrivelse: "Dat6 ære",
        anti: true,
        konklusion: [
            "Strube",
            "FUNÉ",
            "Panini",
            "Asbjørn",
            "Nickolaj",
            "Jacob W.",
            "Niels Jakob"
        ]
    },
    {
        klander: ["Hjalte"],
        klandret: ["Mikkel Mus"],
        beskrivelse: "Dat6 bank",
        anti: true,
        konklusion: [
            "Hjalte",
            "Emil S.",
            "Nickolaj",
            "Niels Jakob",
            "FUNÉ",
        ]
    },
    {
        klander: ["Jacob W."],
        klandret: ["Nickolaj"],
        beskrivelse: "faldt på cykel",
        med: 3,
        mod: 13,
    },
    {
        klander: ["Panini"],
        klandret: ["FUNÉ"],
        beskrivelse: "Beskeder",
        med: 14,
        mod: 7,
    },
    {
        klander: ["Hjalte"],
        klandret: ["Jacob W."],
        beskrivelse: "Urimlig klandring",
        med: 15,
        mod: 15,
    },
    {
        klander: ["FUNÉ"],
        klandret: ["Panini"],
        beskrivelse: "Sover i timen",
        med: 13,
        mod: 5,
    },
    {
        klander: ["Nickolaj"],
        klandret: ["Panini"],
        beskrivelse: "Jacob?",
        med: 14,
        mod: 1,
    },
    // 17. september 2021
    {
        klander: ["Jacob W."],
        klandret: ["Højre- og Venstre-knæ"],
        beskrivelse: "Disjoint",
        med: 17,
        mod: 14,
    },
    {
        klander: ["Jacob W."],
        klandret: ["Emil S."],
        beskrivelse: "Sten sakts tommel up",
        med: 12,
        mod: 15,
    },
    {
        klander: ["Jacob W."],
        klandret: ["Niels Jakob"],
        beskrivelse: "Inprog",
        med: 18,
        mod: 7,
    },
    {
        klander: ["Emil S."],
        klandret: ["FUNÉ"],
        beskrivelse: "Kahoot",
        med: 18,
        mod: 17,
    },
    {
        klander: ["Benjamin"],
        klandret: ["FUNÉ"],
        beskrivelse: "Hvem er Mikkel",
        med: 17,
        mod: 15,
    },
    {
        klander: ["Panini"],
        klandret: ["FUNÉ"],
        beskrivelse: "T-Shirt",
        med: 6,
        mod: 17,
    },
    {
        klander: ["Jacob R."],
        klandret: ["Hjalte"],
        beskrivelse: "Hemmelighed",
        med: 18,
        mod: 17,
    },
    {
        klander: ["Alexander"],
        klandret: ["Dolan"],
        beskrivelse: "Vindertrøje",
        med: 18,
        mod: 3,
    },
    {
        klander: ["Hjalte"],
        klandret: ["Jacob W."],
        beskrivelse: "Dårlig joke",
        med: 16,
        mod: 16,
    },
    {
        klander: ["Mikkel mus"],
        klandret: ["Strube"],
        beskrivelse: "Lokale",
        med: 18,
        mod: 15,
    },
    {
        klander: ["Nickolaj"],
        klandret: ["Panini"],
        beskrivelse: "Armlægning",
        med: 17,
        mod: 1,
    },
    {
        klander: ["Panini"],
        klandret: ["Strube"],
        beskrivelse: "False advertisment",
        aldrigsket: true,
    },
    {
        klander: ["Niels Jakob"],
        klandret: ["Strube"],
        beskrivelse: "Økochef",
        med: 18,
        mod: 16,
    },
    {
        klander: ["Niels Jakob"],
        klandret: ["Strube"],
        beskrivelse: "Twister",
        med: 17,
        mod: 16,
    },
    {
        klander: ["Strube"],
        klandret: ["Dolan"],
        beskrivelse: "Fyret",
        med: 14,
        mod: 6,
    },
    {
        klander: ["Panini"],
        klandret: ["FUNÉ"],
        beskrivelse: "HH",
        med: 9,
        mod: 16,
    },
    {
        anti: true,
        klander: ["Alexander"],
        klandret: ["Jacob R."],
        beskrivelse: "Klandre hjemmeside",
        konklusion: ["Alexander", "Hjalte", "Benjamin", "FUNÉ"]
    },
    {
        klander: ["Dolan"],
        klandret: ["Emil S."],
        beskrivelse: "våd",
        med: 11,
        mod: 11,
    },
    {
        anti: true,
        klander: ["Jacob W."],
        klandret: ["Morten"],
        beskrivelse: "a",
        konklusion: ["Jacob W.", "Emil S.", "Nickolaj", "Jacob R.", "Hjalte"]
    },
    {
        klander: ["Hjalte"],
        klandret: ["Emil S.", "Jacob W."],
        beskrivelse: "TK åbningstid",
        med: 8,
        mod: 5,
    },
    {
        klander: ["FUNÉ"],
        klandret: ["Panini"],
        beskrivelse: "mødetid?",
        med: 11,
        mod: 10,
    },
    {
        klander: ["Emil S."],
        klandret: ["Panini"],
        beskrivelse: "Plagiat",
        med: 13,
        mod: 12,
    },
    {
        anti: true,
        klander: ["Jacob R."],
        klandret: ["Panini"],
        beskrivelse: "Fødselsdag",
        konklusion: ["Jacob R.", "Hjalte", "Emil S.", "Morten"]
    },
    {
        klander: ["Hjalte"],
        klandret: ["Dolan"],
        beskrivelse: "Sketchy forklaring",
        med: 12,
        mod: 5,
    },
]